/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FailedIngest {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  url: string;
}

export interface Ingredient {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  label: string;
  recipe_id: number;
  sort: number | null;
  unit_id: number | null;
}

export interface Recipe {
  category: string | null;
  created_at: Generated<Timestamp | null>;
  cuisine: string | null;
  description: string | null;
  id: Generated<Int8>;
  keywords: string | null;
  name: string;
  primary_image: string | null;
  url: string | null;
  uuid: Generated<string>;
}

export interface Steps {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  label: string;
  recipe_id: number;
  section: string | null;
  sort: number;
  text: string | null;
}

export interface Unit {
  abbreviation: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  label: string;
}

export interface UserRecipe {
  created_at: Generated<Timestamp>;
  recipe_id: Int8;
  user_id: Int8;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  name: string | null;
}

export interface DB {
  failed_ingest: FailedIngest;
  ingredient: Ingredient;
  recipe: Recipe;
  steps: Steps;
  unit: Unit;
  user_recipe: UserRecipe;
  users: Users;
}
